### ISSUE TITLE
On s'y met quand ?

### ISSUE THREAD

**Issue by nobrakal** [IP7/website#1]
@IP7/bureau ?

**Comment by elusyo** [comment]
Je ne fais pas parti de l'équipe de travail du site mais je me posais la même question :+1:

**Comment by FauconFan** [comment]
Faut qu'on s'appelle pour en discuter

**Comment by elusyo** [comment]
Je vous laisse faire

**Comment by Peaupote** [comment]
On a un cahier des charges quelque part ? Je me souviens plus de ce qu'on avait conclu pour le site.

**Comment by nobrakal** [comment]
Mmhh de mémoire non,

À mon avis faudrait un truc du genre blog, avec des billets qui défilent et un "espace membre".

@elusyo avait eu l'idée d'un wiki en plus, j'aime bien aussi

**Comment by nobrakal** [comment]
@Peaupote On peut supprimer tout le code go déjà ?

**Comment by Peaupote** [comment]
Oui, je pense qu'on peut tout balancer sans regrets

**Comment by nobrakal** [comment]
Fait: https://github.com/IP7/website/commit/ab41bb092f7a7f69320a2d72e105e4a074e63c9c

**Comment by FauconFan** [comment]
Bah c'est fini
